// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Color color object
// swagger:model Color
type Color struct {

	// color in hex
	Hex string `json:"hex,omitempty"`

	// color Id
	ID int32 `json:"id,omitempty"`

	// item name
	Name string `json:"name,omitempty"`

	// pin code name
	PinCode string `json:"pinCode,omitempty"`
}

// Validate validates this color
func (m *Color) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Color) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Color) UnmarshalBinary(b []byte) error {
	var res Color
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
