required = [
    "github.com/go-swagger/go-swagger/cmd/swagger",
    "github.com/golangci/golangci-lint/cmd/golangci-lint",
]

[[constraint]]
  version = "v1.12.5"
  name = "github.com/golangci/golangci-lint"

[[constraint]]
  name = "github.com/apex/log"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[override]]
  version = "v0.17.0"
  name = "github.com/go-swagger/go-swagger"

[prune]
  go-tests = true
  unused-packages = true
