version: '3.5'
services:
  mysqldb:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test:
        - CMD-SHELL
        - echo 'SHOW tables;' | mysql -unimses -pnimses -Dnimses
      interval: 5s
      timeout: 10s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: onetwoclimb
      MYSQL_DATABASE: onetwoclimb
      MYSQL_USER: onetwoclimb
      MYSQL_PASSWORD: onetwoclimb
      MYSQL_ROOT_HOST: "%"