// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"

	models "github.com/onetwoclimb/internal/server/models"
)

// BoardColorsHandlerFunc turns a function with the right signature into a board colors handler
type BoardColorsHandlerFunc func(BoardColorsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BoardColorsHandlerFunc) Handle(params BoardColorsParams) middleware.Responder {
	return fn(params)
}

// BoardColorsHandler interface for that can handle valid board colors params
type BoardColorsHandler interface {
	Handle(BoardColorsParams) middleware.Responder
}

// NewBoardColors creates a new http.Handler for the board colors operation
func NewBoardColors(ctx *middleware.Context, handler BoardColorsHandler) *BoardColors {
	return &BoardColors{Context: ctx, Handler: handler}
}

/*BoardColors swagger:route GET /colors boardColors

get board colors

*/
type BoardColors struct {
	Context *middleware.Context
	Handler BoardColorsHandler
}

func (o *BoardColors) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBoardColorsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// BoardColorsOKBody board colors o k body
// swagger:model BoardColorsOKBody
type BoardColorsOKBody struct {

	// colors
	// Required: true
	Colors []*models.Color `json:"colors"`
}

// Validate validates this board colors o k body
func (o *BoardColorsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateColors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BoardColorsOKBody) validateColors(formats strfmt.Registry) error {

	if err := validate.Required("boardColorsOK"+"."+"colors", "body", o.Colors); err != nil {
		return err
	}

	for i := 0; i < len(o.Colors); i++ {
		if swag.IsZero(o.Colors[i]) { // not required
			continue
		}

		if o.Colors[i] != nil {
			if err := o.Colors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("boardColorsOK" + "." + "colors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *BoardColorsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BoardColorsOKBody) UnmarshalBinary(b []byte) error {
	var res BoardColorsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
