// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/onetwoclimb/internal/server/models"
)

// BoardColorsOKCode is the HTTP code returned for type BoardColorsOK
const BoardColorsOKCode int = 200

/*BoardColorsOK OK

swagger:response boardColorsOK
*/
type BoardColorsOK struct {

	/*
	  In: Body
	*/
	Payload *BoardColorsOKBody `json:"body,omitempty"`
}

// NewBoardColorsOK creates BoardColorsOK with default headers values
func NewBoardColorsOK() *BoardColorsOK {

	return &BoardColorsOK{}
}

// WithPayload adds the payload to the board colors o k response
func (o *BoardColorsOK) WithPayload(payload *BoardColorsOKBody) *BoardColorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the board colors o k response
func (o *BoardColorsOK) SetPayload(payload *BoardColorsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardColorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// BoardColorsInternalServerErrorCode is the HTTP code returned for type BoardColorsInternalServerError
const BoardColorsInternalServerErrorCode int = 500

/*BoardColorsInternalServerError General server error. Error codes:
  - 4 Server error

swagger:response boardColorsInternalServerError
*/
type BoardColorsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBoardColorsInternalServerError creates BoardColorsInternalServerError with default headers values
func NewBoardColorsInternalServerError() *BoardColorsInternalServerError {

	return &BoardColorsInternalServerError{}
}

// WithPayload adds the payload to the board colors internal server error response
func (o *BoardColorsInternalServerError) WithPayload(payload *models.Error) *BoardColorsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the board colors internal server error response
func (o *BoardColorsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardColorsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
