// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// BoardColorsOKCode is the HTTP code returned for type BoardColorsOK
const BoardColorsOKCode int = 200

/*BoardColorsOK OK

swagger:response boardColorsOK
*/
type BoardColorsOK struct {

	/*
	  In: Body
	*/
	Payload *BoardColorsOKBody `json:"body,omitempty"`
}

// NewBoardColorsOK creates BoardColorsOK with default headers values
func NewBoardColorsOK() *BoardColorsOK {

	return &BoardColorsOK{}
}

// WithPayload adds the payload to the board colors o k response
func (o *BoardColorsOK) WithPayload(payload *BoardColorsOKBody) *BoardColorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the board colors o k response
func (o *BoardColorsOK) SetPayload(payload *BoardColorsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardColorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
