// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/onetwoclimb/internal/server/models"
)

// GetBoardColorsOKCode is the HTTP code returned for type GetBoardColorsOK
const GetBoardColorsOKCode int = 200

/*GetBoardColorsOK OK

swagger:response getBoardColorsOK
*/
type GetBoardColorsOK struct {

	/*
	  In: Body
	*/
	Payload *GetBoardColorsOKBody `json:"body,omitempty"`
}

// NewGetBoardColorsOK creates GetBoardColorsOK with default headers values
func NewGetBoardColorsOK() *GetBoardColorsOK {

	return &GetBoardColorsOK{}
}

// WithPayload adds the payload to the get board colors o k response
func (o *GetBoardColorsOK) WithPayload(payload *GetBoardColorsOKBody) *GetBoardColorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get board colors o k response
func (o *GetBoardColorsOK) SetPayload(payload *GetBoardColorsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardColorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBoardColorsInternalServerErrorCode is the HTTP code returned for type GetBoardColorsInternalServerError
const GetBoardColorsInternalServerErrorCode int = 500

/*GetBoardColorsInternalServerError General server error. Error codes:
  - 4 Server error

swagger:response getBoardColorsInternalServerError
*/
type GetBoardColorsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBoardColorsInternalServerError creates GetBoardColorsInternalServerError with default headers values
func NewGetBoardColorsInternalServerError() *GetBoardColorsInternalServerError {

	return &GetBoardColorsInternalServerError{}
}

// WithPayload adds the payload to the get board colors internal server error response
func (o *GetBoardColorsInternalServerError) WithPayload(payload *models.Error) *GetBoardColorsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get board colors internal server error response
func (o *GetBoardColorsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardColorsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
