// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostBoardColorsHandlerFunc turns a function with the right signature into a post board colors handler
type PostBoardColorsHandlerFunc func(PostBoardColorsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBoardColorsHandlerFunc) Handle(params PostBoardColorsParams) middleware.Responder {
	return fn(params)
}

// PostBoardColorsHandler interface for that can handle valid post board colors params
type PostBoardColorsHandler interface {
	Handle(PostBoardColorsParams) middleware.Responder
}

// NewPostBoardColors creates a new http.Handler for the post board colors operation
func NewPostBoardColors(ctx *middleware.Context, handler PostBoardColorsHandler) *PostBoardColors {
	return &PostBoardColors{Context: ctx, Handler: handler}
}

/*PostBoardColors swagger:route POST /colors postBoardColors

post board colors

*/
type PostBoardColors struct {
	Context *middleware.Context
	Handler PostBoardColorsHandler
}

func (o *PostBoardColors) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBoardColorsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
