// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi OneTwoClimb API

    Schemes:
      http
    Host: localhost
    BasePath: /api/v1.0
    Version: 1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
