swagger: '2.0'
info:
  title: OneTwoClimb API
  version: '1.0'
basePath: /api/v1.0
schemes:
  - http
produces:
  - application/json

paths:
  /colors:
    get:
      summary: get board colors
      operationId: getBoardColors
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              colors:
                type: array
                items:
                  $ref: "#/definitions/Color"
            required:
              - colors
        500:
          description: General server error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: post board colors
      operationId: postBoardColors
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            type: object
            $ref: "#/definitions/Color"
      responses:
        200:
          description: OK
        500:
          description: General server error
          schema:
            $ref: "#/definitions/Error"

  /colors/{colorId}:
    delete:
      summary: delete borad color
      operationId: delBoardColor
      parameters:
        - $ref: "#/parameters/colorId"
      responses:
        200:
          description: OK
        500:
          description: General server error
          schema:
            $ref: "#/definitions/Error"
  /upload:
    post:
      operationId: uploadFile
      summary: Upload image
      description: "The file can't be larger than **5MB**"
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: The file to upload
          type: file
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                description: image id
            required:
              - id
        500:
          description: General server error
          schema:
            $ref: "#/definitions/Error"
  /download:
    get:
      operationId: downloadFile
      summary: Download image
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: download file OK
          schema:
            type: string
            format: byte
        400:
          description: Bad Argument
          schema:
            $ref: "#/definitions/Error"
        500:
          description: General server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: File not found
          schema:
            $ref: "#/definitions/Error"
parameters:
  colorId:
    name: colorId
    in: path
    type: integer
    format: int32
    description: color ID
    required: true
  id:
    name: id
    in: query
    type: string
    description: image id
    required: true

definitions:
  Color:
    description: color object
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: color Id
      name:
        type: string
        description: item name
      hex:
        type: string
        description: color in hex
      pinCode:
        type: string
        description: pin code name

  Error:
    type: object
    properties:
      code:
        type: integer
        description: internal status code
      message:
        type: string
    required:
      - code
      - message

