swagger: '2.0'
info:
  title: OneTwoClimb API
  version: '1.0'
basePath: /api/v1.0
schemes:
  - http
produces:
  - application/json

paths:
  /colors:
    get:
      summary: get board colors
      operationId: getBoardColors
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              colors:
                type: array
                items:
                  $ref: "#/definitions/Color"
            required:
              - colors
        500:
          description: >-
            General server error.
            Error codes:
              - 4 Server error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: post board colors
      operationId: postBoardColors
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            type: object
            $ref: "#/definitions/Color"
      responses:
        200:
          description: OK
        500:
          description: >-
            General server error.
            Error codes:
              - 4 Server error
          schema:
            $ref: "#/definitions/Error"

  /colors/{colorId}:
    delete:
      summary: delete borad color
      operationId: delBoardColor
      parameters:
        - $ref: "#/parameters/colorId"
      responses:
        200:
          description: OK
        500:
          description: >-
            General server error.
            Error codes:
              - 4 Server error
          schema:
            $ref: "#/definitions/Error"

parameters:
  colorId:
    name: colorId
    in: path
    type: integer
    format: int32
    description: color ID
    required: true

definitions:
  Color:
    description: color object
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: color Id
      name:
        type: string
        description: item name
      hex:
        type: string
        description: color in hex
      pinCode:
        type: string
        description: pin code name

  Error:
    type: object
    properties:
      code:
        type: integer
        description: internal status code
      message:
        type: string
    required:
      - code
      - message

