swagger: '2.0'
info:
  title: OneTwoClimb API
  version: '1.0'
basePath: /api/v1.0
schemes:
  - http
produces:
  - application/json

paths:
  /colors:
    get:
      summary: get board colors
      operationId: boardColors
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              colors:
                type: array
                items:
                  $ref: "#/definitions/Color"
            required:
              - colors
        500:
          description: >-
            General server error.
            Error codes:
              - 4 Server error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Color:
    description: color object
    type: object
    properties:
      id:
        type: integer
        description: color id
      name:
        type: string
        description: item name
      hex:
        type: string
        description: color in hex
      pinCode:
        type: string
        description: pin code name

  Error:
    type: object
    properties:
      code:
        type: integer
        description: internal status code
      message:
        type: string
    required:
      - code
      - message
